---
title: "Run Mizer with ZooMizer as a resource"
author: "Patrick Sykes"
date: "26/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Set up the model

Load in required libraries and functions:

```{r libraries}

library(mizer)
library(tidyverse)
library(assertthat)
source("ZooMizerResourceFunctions.R")
```

Now the data needed to run the model
```{r data}

groups <- read.csv("data/TestGroups_mizer.csv") #load in ZooMSS groups
zoo_groups <- groups[which(groups$Type == "Zooplankton"),] #just keep the zooplankton

ID <- 18  # pick a row to use of the environment data
input <- readRDS("data/enviro_test20.RDS")[ID,]

```

We now build the model:

```{r setup_params}

# read in zooplankton at stable state for initial values

## FROM ZOOMSS
# stable_zoo <- readRDS("zoomssgrid_redo_yearly.rds")[[ID]] #read in from ZooMSS (benefit of this method is that we can use the Matrix)

## FROM ZOOMIZER
stable_zoomizer <- readRDS("test_grid_20210317.RDS")[[ID]]

intercept <- mean(getCommunitySlope(stable_zoomizer #,
                                    #species = c("Fish_Small", "Fish_Med", "Fish_Large")
                                    )$intercept[501:1000])
slope <- mean(getCommunitySlope(stable_zoomizer #,
                                #species = c("Fish_Small", "Fish_Med", "Fish_Large")
                                )$slope[501:1000])

f <- function(x) exp(intercept) * x^(slope)
g <- function(x) 10^input$phyto_int * x^(input$phyto_slope)
plotSpectra(stable_zoomizer, species = c("Fish_Small", "Fish_Med", "Fish_Large"))+geom_function(fun = f)+geom_function(fun = g)


times <- length(getTimes(stable_zoomizer))
stable_zoo <- colSums(stable_zoomizer@n[ceiling(times/2):times,,])

# new <- zoo_params@initial_n * 0
# 
# w_mins <- zoo_groups$w_min
# w_maxs <- zoo_groups$w_inf
# w_min_idx <- zoo_params@w_min_idx
# w_max_idx <- w_min_idx
# 
# for (i in 1:length(w_max_idx)) {
#   w_max_idx[i] <- max(which(zoo_params@w <= zoo_params@species_params$w_inf[i]))
# }
# zoomizer_w <- seq(from = -10.7, to = 7, by = 0.1)
# 
# for (i in 1:nrow(new)) {
#   new[i,w_min_idx[i]:(w_max_idx[i])] <- spline(zoomizer_w, y = stable_zoo[i,], # method = "fmm",
#                                             xout = log10(zoo_params@w),
#                                             ties = mean
#                                             )$y[w_min_idx[i]:(w_max_idx[i])] 
#   new[i,] <- apply(cbind(as.data.frame(new[i,]), 0), 1, max)
#   # only include this line if importing from ZooMSS
#   # new[i, ] <- new[i, ] / zoo_params@dw
# }

new <- stable_zoo[which(groups$Type == "Zooplankton"),]

# fish_params <- NS_params  # or any other mizer params object
# fish_params <- newMultispeciesParams(species_params = NS_species_params,
#                                      interaction = inter,
#                                      min_w_pp = 10^(-14.5),
#                                      #gear_params = NS_species_params_gears
#                                      kappa = 10^(input$phyto_int),
#                                      lambda = 1-input$phyto_slope
#                                      )

temp_eff <- 2.^((input$sst - 30)/10)

fish_params <- newTraitParams(no_sp = 3,
                              min_w = 10^(-3),
                              min_w_inf = 10^3,
                              max_w_inf = 10^7,
                              no_w = (7-(-3))*10+1, # sets dx = 0.1 basically
                              min_w_pp = 10^(-14.5),
                              alpha = 0.25 * temp_eff, #takes care of assimilation efficiency & temp effect on Encounter
                              kappa = exp(intercept), #10^(input$phyto_int) * 10^-1,
                              lambda = 1 - slope, # 1 - input$phyto_slope,
                              gamma = 640 * temp_eff, #takes care of temp effect on PredRate
                              R_factor = Inf,
                              ext_mort_prop = 0.1,
                              knife_edge_size = 10  # min size for fishing
                              )

fish_params@species_params$gamma <- 640 * temp_eff
fish_params <- setSearchVolume(fish_params)

zoo_params <- newZooMizerParams(groups = zoo_groups, input = input, fish_params = fish_params)

zoo_params@initial_n <- new[1:9,]

fish_params <- fish_params %>%
    setComponent(component = "zoo",
                 initial_value = zoo_params@initial_n,
                 dynamics_fun = "zoo_dynamics",
                 component_params = list(params = zoo_params)
                 ) %>%
    setResource(resource_dynamics = "resource_zooMizer")

PredRate_temp <- function (params, n, n_pp, n_other, t, feeding_level, ...) 
{
  no_sp <- dim(params@interaction)[1]
  no_w <- length(params@w)
  no_w_full <- length(params@w_full)
  if (length(params@ft_pred_kernel_p) == 1) {
    n_total_in_size_bins <- sweep(n, 2, params@dw, "*", 
      check.margin = FALSE)
    pred_rate <- sweep(params@pred_kernel, c(1, 2), (1 - 
      feeding_level) * params@search_vol * n_total_in_size_bins, 
      "*", check.margin = FALSE)
    pred_rate <- colSums(aperm(pred_rate, c(2, 1, 3)), dims = 1)
    return(pred_rate * params@other_params$temp_eff)
  }
  idx_sp <- (no_w_full - no_w + 1):no_w_full
  Q <- matrix(0, nrow = no_sp, ncol = no_w_full)
  Q[, idx_sp] <- sweep((1 - feeding_level) * params@search_vol * 
    n, 2, params@dw, "*")
  pred_rate <- Re(t(mvfft(t(params@ft_pred_kernel_p) * mvfft(t(Q)), 
    inverse = TRUE)))/no_w_full
  pred_rate[pred_rate < 1e-18] <- 0
  return(pred_rate * params@ft_mask * params@other_params$temp_eff)
}

fish_params <- setRateFunction(fish_params, "PredRate", "PredRate_temp")

fish_params@other_params$temp_eff <- 2.^((input$sst - 30)/10)

initialNResource(fish_params) <- resource_zooMizer(fish_params, fish_params@initial_n_other) #TODO: set this to be stable state of a regular ZooMizer run

plotSpectra(fish_params, wlim = c(10^-14.5, NA), total = FALSE)




fish_params <- setParams(fish_params)

getRDI(fish_params)

```


And run it:

```{r run}
tmax <- 100
sim <- project(fish_params, t_max = tmax, dt = 0.1)
plot(sim)
(fish_plot <- plotSpectra(sim,
                          wlim = c(sim@params@w_full[1], 10^7),
                          time_range = c(ceiling(tmax/2), tmax),
                          #ylim = c(1e-09, NA),
                          total = TRUE)+
    labs(title = paste("ZooMizer + Mizer, average spectrum over last half of", tmax, "year run")) )#+
    # scale_color_manual(labels = c("Fish_Small", "Fish_Med", "Fish_Large", "Resource","Total"), values = sim@params@linecolour)

```

```{r animation}
library(plotly)

animateSpectra(sim, wlim = c(1e-10, 1e7), ylim = c(1e-450, NA))

## old code no longer needed since the `animateSpectra` function is now included in Mizer...
#
# melt(N(sim)) %>% 
#     filter(value > 0) %>%
#     plot_ly() %>% 
#     add_lines(x = ~w, y = ~value, 
#               color = ~as.factor(sp), colors = getColours(sim@params),
#               frame = ~time,
#               line = list(simplify = FALSE)) %>% 
#     layout(xaxis = list(type = "log", exponentformat = "power"),
#            yaxis = list(type = "log", exponentformat = "power", range = c(-500, 10)))

```

The trait model sets up reproductive efficiencies based on power-law resource. But we're using ZooMizer as the resource, so we ought to retune the reproductive efficiency.

```{r}

steady_fish <-  steady(fish_params, return_sim = TRUE, dt = 0.1, t_per = 1.5, tol = 1)
plotBiomass(steady_fish)
plotSpectra(steady_fish)

tuned_erepro <- retune_erepro(steady_fish) #NB this doesn't seem to do anything for the trait-based model

tuned_sim <- project(tuned_erepro, t_max = 10, dt = 0.1)

```

```{r plots}
plotSpectra(sim, wlim = c(tuned_sim@params@w_full[1], 1000))+labs(title = "Untuned model")
plotSpectra(tuned_sim, wlim = c(tuned_sim@params@w_full[1], 1000))+labs(title="tuned model")

```

Worth comparing this to ZooMizer running as ZooMSS:

```{r comparison}

zoomizer_standard <- readRDS("test_grid_20210317.RDS")[[ID]]
zoomizer_plot <- zoomizer_standard
zoomizer_plot@n_pp <- zoomizer_plot@n_pp*0

(standard_plot <- plotSpectra(zoomizer_plot, resource = FALSE, wlim = c(sim@params@w_full[1], 10^7), time_range = c(ceiling(tmax/2), tmax), total = TRUE, ylim = c(1e-09, 1e+09))+labs(title = paste("'Standard' ZooMizer, average spectrum over last half of", tmax, "year run")))

library(patchwork)

(p <- standard_plot / fish_plot)

```


```{r}


# 
# fish_params@other_params$assim_eff <- 0.1 * 2.5  #10% carbon * 2.5 GGE scaling factor
# fish_params@other_params$temp_eff <- 2.^((input$sst - 30)/10)
# 
# new_fish_Encounter <- function (params, n, n_pp, n_other, t, ...) 
# {
#     idx_sp <- (length(params@w_full) - length(params@w) + 1):length(params@w_full)
#     assim_prey <- params@other_params$assim_eff * params@interaction
#     if (length(params@ft_pred_kernel_e) == 1) {
#         n_eff_prey <- sweep(assim_prey %*% n, 2,
#                       params@w * params@dw, "*", check.margin = FALSE)
#         phi_prey_species <- rowSums(sweep(params@pred_kernel[, 
#             , idx_sp, drop = FALSE], c(1, 3), n_eff_prey, "*", 
#             check.margin = FALSE), dims = 2)
#         phi_prey_background <- params@species_params$interaction_resource * 
#             rowSums(sweep(params@pred_kernel, 3, params@dw_full * 
#                 params@w_full * n_pp, "*", check.margin = FALSE), 
#                 dims = 2)
#         encounter <- params@search_vol * (phi_prey_species + 
#             phi_prey_background)
#     }
#     else {
#         prey <- outer(params@species_params$interaction_resource, 
#             n_pp)
#         prey[, idx_sp] <- prey[, idx_sp] + assim_prey %*% 
#             n
#         prey <- sweep(prey, 2, params@w_full * params@dw_full, 
#             "*")
#         avail_energy <- Re(base::t(mvfft(base::t(params@ft_pred_kernel_e) * 
#             mvfft(base::t(prey)), inverse = TRUE)))/length(params@w_full)
#         avail_energy <- avail_energy[, idx_sp, drop = FALSE]
#         avail_energy[avail_energy < 1e-18] <- 0
#         encounter <- params@search_vol * avail_energy
#     }
#     for (i in seq_along(params@other_encounter)) {
#         encounter <- encounter + do.call(params@other_encounter[[i]], 
#             list(params = params, n = n, n_pp = n_pp, n_other = n_other, 
#                 component = names(params@other_encounter)[[i]], 
#                 ...))
#     }
#     return(encounter * params@other_params$temp_eff)
# }
# 
# new_fish_PredRate <- function (params, n, n_pp, n_other, t, feeding_level, ...) 
# {
#     no_sp <- dim(params@interaction)[1]
#     no_w <- length(params@w)
#     no_w_full <- length(params@w_full)
#     if (length(params@ft_pred_kernel_p) == 1) {
#         n_total_in_size_bins <- sweep(n, 2, params@dw, "*", 
#             check.margin = FALSE)
#         pred_rate <- sweep(params@pred_kernel, c(1, 2), (1 - 
#             feeding_level) * params@search_vol * n_total_in_size_bins, 
#             "*", check.margin = FALSE)
#         pred_rate <- colSums(aperm(pred_rate, c(2, 1, 3)), dims = 1)
#         return(pred_rate * params@other_params$temp_eff)
#     }
#     idx_sp <- (no_w_full - no_w + 1):no_w_full
#     Q <- matrix(0, nrow = no_sp, ncol = no_w_full)
#     Q[, idx_sp] <- sweep((1 - feeding_level) * params@search_vol * 
#         n, 2, params@dw, "*")
#     pred_rate <- Re(t(mvfft(t(params@ft_pred_kernel_p) * mvfft(t(Q)), 
#         inverse = TRUE)))/no_w_full
#     pred_rate[pred_rate < 1e-18] <- 0
#     return(pred_rate * params@ft_mask * params@other_params$temp_eff)
# }
# 
# fish_params <- setRateFunction(fish_params, "Encounter", "new_fish_Encounter")
# fish_params <- setRateFunction(fish_params, "PredRate", "new_fish_PredRate")

```
