---
title: "Un-hardwiring ZooMizer"
author: "Patrick Sykes"
date: "16/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mizer)
library(assertthat)
library(tidyverse)
```

## Load in basic data

```{r data}

ID <- 10

control <- readRDS("test_grid_20210309.RDS")[[ID]]

enviro_row <- readRDS("data/enviro_test20.RDS")[ID,]


groups <- read.csv("data/TestGroups_mizer.csv")

```

## Run updated version

```{r run}

source("fZooMizer_run.R")

environment(new_project_simple) <- asNamespace('mizer')
assignInNamespace("project_simple", new_project_simple, ns = "mizer")

#environment(new_newMultispeciesParams) <- asNamespace('mizer')
#assignInNamespace("newMultispeciesParams", new_newMultispeciesParams, ns = "mizer")

#environment(new_emptyParams) <- asNamespace('mizer')
#assignInNamespace("emptyParams", new_emptyParams, ns = "mizer")


enviro_row$tmax <- 10

new <- fZooMizer_run(groups, enviro_row)

sum(new@n_pp[1,]>0) == sum(control@n_pp[1,] >0)

all.equal(new@n_pp[1,], control@n_pp[1,])
all.equal(new@n[1,,], control@n[1,,])
#all.equal(new@params@search_vol, control@params@search_vol)
#all.equal(new@params@mu_b, control@params@mu_b)


all.equal(new@params@w_full, control@params@w_full)

all.equal(new@n[2,,], control@n[2,,])
all.equal(new@n[enviro_row$tmax+1,,], control@n[enviro_row$tmax+1,,])

```


## Useful plots

```{r plots}

plot(control)
plot(new)

(p1 <- plotBiomass(control, start_time = 0, end_time = enviro_row$tmax)+labs(title = "Control - ZooMizer with hardwiring"))
(p2 <- plotBiomass(new, start_time = 0, end_time = enviro_row$tmax)+labs(title = "ZooMizer withOUT hardwiring"))

plotSpectra(control, time_range = enviro_row$tmax)+labs(title = paste("Control at", enviro_row$tmax, "years"))
plotSpectra(new, time_range = enviro_row$tmax)+labs(title = paste("New at", enviro_row$tmax, "years"))

plotSpectra(control, time_range = c(ceiling(enviro_row$tmax/2), enviro_row$tmax))+labs(title = paste("Control last", ceiling(enviro_row$tmax/2), "years"))
plotSpectra(new, time_range = c(ceiling(enviro_row$tmax/2), enviro_row$tmax))+labs(title = paste("New last", ceiling(enviro_row$tmax/2), "years"))

```

